//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altre.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Payments = new HashSet<Payments>();
            this.PermConct = new HashSet<PermConct>();
        }
    
        public int employee_id { get; set; }
        public int position_id { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public string last_name { get; set; }
        public System.DateTime birthday { get; set; }
        public int gndr_id { get; set; }
        public string inn { get; set; }
        public string snils { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public System.DateTime employment_date { get; set; }
        public Nullable<System.DateTime> termination_date { get; set; }
        public string termination_reason { get; set; }
        public byte[] photo { get; set; }
    
        public virtual Gndr Gndr { get; set; }
        public virtual Positions Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermConct> PermConct { get; set; }
    }
}
