//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altre.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int payment_id { get; set; }
        public int employee_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public int paymenttype_id { get; set; }
        public decimal amount { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
