//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Altre.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermConct
    {
        public int user_id { get; set; }
        public int employee_id { get; set; }
        public string description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Users Users { get; set; }
    }
}
